### PR TITLE
chore(py): bump Python floor to 3.13 (#113)

### LINKED ISSUE #113: Test failure: typing.is_protocol requires Python 3.13 but env pins 3.12
## Summary

`tests/test_memory_protocol.py::TestMemoryBackendProtocol::test_protocol_is_a_protocol` fails on `origin/main` because it imports `typing.is_protocol`, which was only added in Python **3.13**. The project's `.python-version` / uv resolution currently pins **3.12.13**.

## Reproduction

```bash
uv run pytest tests/test_memory_protocol.py::TestMemoryBackendProtocol::test_protocol_is_a_protocol
```

## Error

```
=================================== FAILURES ===================================
____________ TestMemoryBackendProtocol.test_protocol_is_a_protocol _____________

self = <tests.test_memory_protocol.TestMemoryBackendProtocol object at 0x10832c350>

    def test_protocol_is_a_protocol(self) -> None:
        """MemoryBackend should be a typing.Protocol subclass."""
>       from typing import is_protocol
E       ImportError: cannot import name 'is_protocol' from 'typing' (/Users/.../cpython-3.12.13-macos-aarch64-none/lib/python3.12/typing.py). Did you mean: 'Protocol'?

tests/test_memory_protocol.py:226: ImportError
```

## Environment

- Python: 3.12.13 (via uv)
- Pytest: 9.0.2
- Platform: darwin (macOS aarch64)
- Branch: `origin/main` HEAD (`f0401bc`)
- Full-suite status at time of discovery: **2156 passed, 1 failed, 1 skipped**

## Scope / Notes

- Exists on `origin/main` HEAD — **not** introduced by PR #112 (issue #101 stale test fix). Discovered while running the full suite from PR #112's branch.
- `typing.is_protocol` landed in [Python 3.13](https://docs.python.org/3/library/typing.html#typing.is_protocol) (CPython PR [gh-104873](https://github.com/python/cpython/pull/104873)).
- `typing_extensions` provides a back-compatible `is_protocol` that works on 3.12.

## Suggested Fixes (pick one)

1. **Swap the import** to `from typing_extensions import is_protocol` (cheapest, no env change).
2. **Bump the project's Python floor** to 3.13 in `pyproject.toml` and `.python-version`, then keep the `typing` import (bigger blast radius — check CI runners, deploy targets, daemon systemd units).
3. **Guard with a version check** and skip the assertion below 3.13 (least preferable — loses coverage).

## Labels

`bug`, `tests`

### PR DESCRIPTION
**Pull request by stephenfeather**
## Summary

Fixes #113. Bump the project's Python floor from **3.12** to **3.13**.

The immediate trigger was `tests/test_memory_protocol.py::TestMemoryBackendProtocol::test_protocol_is_a_protocol` failing on `main` because it imports `typing.is_protocol`, which was added in Python 3.13. With the floor at `>=3.12`, uv resolved 3.12.13 and the test hit `ImportError`. Bumping the floor gives `typing.is_protocol` from stdlib, closing the class of "version-gap" bugs this represents.

## Scope

Large Plan Workflow (3 adversarial review rounds + Aegis + full-suite evidence). Plan: `thoughts/shared/plans/issue-113-python-313-bump.md`.

### Changed

| File | Change |
|---|---|
| `pyproject.toml` | `requires-python >=3.12` → `>=3.13` |
| `pyproject.toml` | `[tool.black|mypy|ruff]` targets/versions `py311`/`3.11` → `py313`/`3.13` (stale since the 3.12 era) |
| `pyproject.toml` | `symbolica-agentica` marker `>= '3.12'` → `>= '3.13'` (kept for discoverability; redundant given `requires-python`) |
| `pyproject.toml` | Dep lower-bound tightening to versions that ship 3.13 wheels: `numpy>=2.1.0`, `psycopg2-binary>=2.9.10`, `tiktoken>=0.8.0`, `jq>=1.11.0`, `psutil>=5.9.8` |
| `.python-version` | **New** file pinning `3.13` — prevents uv drift back to 3.12 |
| `uv.lock` | Regenerated via `uv lock --upgrade` against 3.13 |
| `docker/Dockerfile.sandbox` | `FROM python:3.12-slim` → `python:3.13-slim` |
| `README.md:73` | "Python 3.12+" → "Python 3.13+" |

### Deliberately not changed

- No runtime code touched. Gemini Round 3 + grep verified: no `crypt`/`pipes` imports, no `asyncio` `loop=` args, no `locale.getdefaultlocale()`, no ABC `.register()` calls, no `asyncio.TaskGroup` usage. One `@runtime_checkable` protocol exists (`scripts/core/db/memory_protocol.py`) and is covered by its own test.
- `scripts/setup/embedded_postgres.py` still creates an isolated pgserver venv on Python 3.12 (`pgserver` has its own Python constraint; this is an architecturally separate helper). Tracked as follow-up in **#116**.

### Full suite on Python 3.13

```
uv run pytest tests/
  ...
  2157 passed, 1 skipped in 27.12s
```

Previous state on `origin/main` was `2156 passed, 1 failed, 1 skipped` — the delta is exactly the `test_protocol_is_a_protocol` fix with zero regressions.

### Stdlib-drift safety net: `-W error::DeprecationWarning`

```
uv run python -W error::DeprecationWarning -m pytest tests/
  ...
  2157 passed, 1 skipped in 4.58s
```

Identical counts with deprecation warnings promoted to errors — evidence that no Python 3.13 stdlib changes are silently emitting deprecations against this codebase.

### Sandbox Dockerfile rebuild

```
docker build -f docker/Dockerfile.sandbox .
  ...
  naming to docker.io/library/opc-sandbox-py313-test:latest done
  unpacking to docker.io/library/opc-sandbox-py313-test:latest 1.4s done
```

Mandatory rebuild verification (per ARCHITECT plan refinement). `python:3.13-slim` image pulled cleanly; all layers built.

### Lockfile regeneration — 46 updates, 3 first-digit bumps (all approved)

| Package | Old | New | Why safe |
|---|---|---|---|
| `more-itertools` | 10.8.0 | 11.0.2 | Transitive-only via `jaraco-classes` / `jaraco-functools` → `keyring` → `py-key-value-aio` → `fastmcp` (agentica extra). Zero direct code contact. |
| `rich` | 14.3.3 | 15.0.0 | `textual` direct dep co-bumped to 8.2.3; resolver enforced a coherent contract. |
| `tzdata` | 2025.3 | 2026.1 | Calendar-versioned zoneinfo database — not semver. |

Zero new transitive packages (all 46 are in-place bumps). Zero yanked versions. Zero downgrades.

## Reviews

- **Adversarial Round 1 (dep compat):** 4 BLOCKER lower-bound bumps flagged (numpy, psycopg2-binary, tiktoken, jq) + 1 WARN (psutil). All adopted into this PR.
- **Adversarial Round 2 (CI/deploy blast radius):** Confirmed no `.github/workflows/`, no mise/asdf/tool-versions, no pre-commit/tox/nox/Pipfile/setup.cfg/readthedocs. Found README.md:73 (folded in) and `scripts/setup/embedded_postgres.py` pgserver venv (deferred to #116).
- **Adversarial Round 3 (3.12 → 3.13 stdlib drift):** No blockers in the codebase. `-W error::DeprecationWarning` full-suite run confirms.
- **Aegis security audit:** LOW risk, APPROVE. All 46 updates are forward bumps with no new CVEs in the version trajectory; `python:3.13-slim` is the same Debian-trixie manifest family as `3.12-slim`; zero yanked versions; zero new transitive deps.
- **Incidental security uplift:** Python 3.13's "dead batteries" removal (`crypt`, `telnetlib`, `pipes`, `imghdr`, `cgi`, etc.) actually *shrinks* the stdlib attack surface available to this project. Security-critical deps also received forward-only patch bumps (`cryptography 46.0.6 → 46.0.7`, `pillow 12.1.1 → 12.2.0`, `aiohttp 3.13.4 → 3.13.5`, `grpcio 1.78.0 → 1.80.0`).

Reviewed with **Gemini-pro** (Codex quota outage) + **Aegis**. Findings: `thoughts/shared/agents/gemini/issue-113-round{1,2,3}-*.md`, `thoughts/shared/agents/aegis/issue-113-audit.md`.

## Follow-ups

- **#116** — Investigate pgserver Python 3.13 support (labeled `enhancement`, `deferred`).
- Non-blocking: recommended future `pip-audit` / OSV cross-check on the new lockfile for completeness (out of scope for this PR).

## Coverage delta

Zero runtime code changed → coverage unchanged.

### CODE REVIEW

**Comment by stephenfeather** [comment]
## Reviewer cycle 1 response

Thanks for the review. Two accepted, two rejected:

**Accepted (commit 4b36407):**
- ✅ **Dockerfile.sandbox inconsistency** — aligned numpy/scipy/sympy floors to match pyproject.toml (numpy>=2.1.0, scipy>=1.16.3, sympy>=1.14.0). Good catch.
- ✅ **symbolica-agentica duplicate in agentica extra** — removed the redundant entry. It was already in main dependencies at >=0.3.1.

**Rejected (with reasoning):**
- ❌ **'jq 1.11.0 does not exist on PyPI'** — [jq 1.11.0](https://pypi.org/pypi/jq/1.11.0/json) does exist; verified via the PyPI JSON API (name='jq', version='1.11.0', 60 wheels shipped, requires_python='>=3.8'). Leaving the pin at `>=1.11.0`. If you have a specific source saying otherwise I'll take another look.
- ❌ **'use typing_extensions instead of bumping Python floor'** — this was an intentional design decision per issue #113. The typing_extensions path was considered but rejected: bumping the floor also closes the broader class of 'test assumes 3.13 stdlib; env pins 3.12' version-gap bugs, aligns the already-stale [tool.black/mypy/ruff] targets that were still on py311, and 3.13 is now widely available. Full-suite green on 3.13 with zero regressions (2156 → 2157, exactly the #113 fix delta). See also the Adversarial Round 2 decision notes in thoughts/shared/agents/gemini/issue-113-round2-ci-deploy.md.

Full suite still green (2157 passed, 1 skipped). Docker rebuild on python:3.13-slim still clean.
