### ISSUE TITLE
Test failure: typing.is_protocol requires Python 3.13 but env pins 3.12

### ISSUE THREAD

**Issue by stephenfeather** [stephenfeather/opc#113]
## Summary

`tests/test_memory_protocol.py::TestMemoryBackendProtocol::test_protocol_is_a_protocol` fails on `origin/main` because it imports `typing.is_protocol`, which was only added in Python **3.13**. The project's `.python-version` / uv resolution currently pins **3.12.13**.

## Reproduction

```bash
uv run pytest tests/test_memory_protocol.py::TestMemoryBackendProtocol::test_protocol_is_a_protocol
```

## Error

```
=================================== FAILURES ===================================
____________ TestMemoryBackendProtocol.test_protocol_is_a_protocol _____________

self = <tests.test_memory_protocol.TestMemoryBackendProtocol object at 0x10832c350>

    def test_protocol_is_a_protocol(self) -> None:
        """MemoryBackend should be a typing.Protocol subclass."""
>       from typing import is_protocol
E       ImportError: cannot import name 'is_protocol' from 'typing' (/Users/.../cpython-3.12.13-macos-aarch64-none/lib/python3.12/typing.py). Did you mean: 'Protocol'?

tests/test_memory_protocol.py:226: ImportError
```

## Environment

- Python: 3.12.13 (via uv)
- Pytest: 9.0.2
- Platform: darwin (macOS aarch64)
- Branch: `origin/main` HEAD (`f0401bc`)
- Full-suite status at time of discovery: **2156 passed, 1 failed, 1 skipped**

## Scope / Notes

- Exists on `origin/main` HEAD — **not** introduced by PR #112 (issue #101 stale test fix). Discovered while running the full suite from PR #112's branch.
- `typing.is_protocol` landed in [Python 3.13](https://docs.python.org/3/library/typing.html#typing.is_protocol) (CPython PR [gh-104873](https://github.com/python/cpython/pull/104873)).
- `typing_extensions` provides a back-compatible `is_protocol` that works on 3.12.

## Suggested Fixes (pick one)

1. **Swap the import** to `from typing_extensions import is_protocol` (cheapest, no env change).
2. **Bump the project's Python floor** to 3.13 in `pyproject.toml` and `.python-version`, then keep the `typing` import (bigger blast radius — check CI runners, deploy targets, daemon systemd units).
3. **Guard with a version check** and skip the assertion below 3.13 (least preferable — loses coverage).

## Labels

`bug`, `tests`
